language: python
cache: pip
notifications:
  email: false
sudo: required
services:
  - docker
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
addons:
  apt:
    packages:
      - openssh-server
      - rpm
      - dpkg
      - cmake
install:
  - pip install flake8 jinja2 sphinx sphinx_rtd_theme
  - sudo ci/install-ssh2.sh
  - python setup.py build_ext --inplace
  - eval "$(ssh-agent -s)"
script:
  - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
  - nosetests
  - flake8 ssh2
  - python setup.py sdist
  - cd dist; pip install *; cd ..
  - cd doc; make html; cd ..
jobs:
  include:

    - stage: build packages
      os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
      install:
        - brew upgrade openssl
        - sudo ci/install-ssh2.sh
        - ls -lh
        - python --version
        - wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
        - sudo python get-pip.py
        - sudo -H pip install -U pip
        - sudo -H pip install -U delocate twine wheel setuptools
        - cp /usr/local/lib/libssh2* .
        - pip wheel .
      script:
        - delocate-listdeps --all *.whl
        - delocate-wheel -v *.whl
        - delocate-listdeps --all *.whl
        - ls -l *.whl
        - rm -f *.dylib
        - pip install --user -v *.whl
        - pwd; mkdir temp; cd temp; pwd
        - python -c "from ssh2.session import Session; Session()"
        - cd ..; pwd
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload -u $PYPI_U -p $PYPI_P *.whl;
          fi
      language: generic
      python: skip

    - stage: build packages
      os: osx
      osx_image: xcode8.3
      before_install:
        - brew update
      install:
        - brew upgrade openssl
        - sudo ci/install-ssh2.sh
        - sudo -H pip2 install -U delocate twine wheel pip setuptools
        - cp /usr/local/lib/libssh2* .
        - ls -lh
        - pip2 wheel .
      script:
        - delocate-listdeps --all *.whl
        - delocate-wheel -v *.whl
        - delocate-listdeps --all *.whl
        - ls -l *.whl
        - rm -f *.dylib
        - pip2 install --user -v *.whl
        - pwd; mkdir temp; cd temp; pwd
        - python -c "from ssh2.session import Session; Session()"
        - cd ..; pwd
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload -u $PYPI_U -p $PYPI_P *.whl;
          fi
      language: generic
      python: skip

    - stage: build packages
      os: osx
      osx_image: xcode8
      before_install:
        - brew update
      install:
        - brew upgrade openssl
        - sudo ci/install-ssh2.sh
        - sudo rm -f libssh2.1.dylib
        - sudo -H pip2 install -U delocate twine wheel pip setuptools
        - cp /usr/local/lib/libssh2* .
        - ls -lh
        - pip2 wheel .
      script:
        - delocate-listdeps --all *.whl
        - delocate-wheel -v *.whl
        - delocate-listdeps --all *.whl
        - ls -l *.whl
        - rm -f *.dylib
        - pip2 install --user -v *.whl
        - pwd; mkdir temp; cd temp; pwd
        - python -c "from ssh2.session import Session; Session()"
        - cd ..; pwd
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload -u $PYPI_U -p $PYPI_P *.whl;
          fi
      language: generic
      python: skip

    - stage: build packages
      os: osx
      osx_image: xcode9.3
      before_install:
        - brew update
      install:
        - brew upgrade openssl
        - sudo ci/install-ssh2.sh
        - sudo -H pip2 install -U delocate twine wheel pip setuptools
        - cp /usr/local/lib/libssh2* .
        - ls -lh
        - pip2 wheel .
      script:
        - delocate-listdeps --all *.whl
        - delocate-wheel -v *.whl
        - delocate-listdeps --all *.whl
        - ls -l *.whl
        - rm -f *.dylib
        - pip2 install --user -v *.whl
        - pwd; mkdir temp; cd temp; pwd
        - python -c "from ssh2.session import Session; Session()"
        - cd ..; pwd
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload -u $PYPI_U -p $PYPI_P *.whl;
          fi
      language: generic
      python: skip

    - stage: build packages
      env:
        - SYSTEM_PACKAGES=1
      os: linux
      language: generic
      python: skip
      install: skip
      script:
        - docker --version
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - ./ci/docker/build-packages.sh
      deploy:
        - provider: releases
          skip_cleanup: true
          api_key:
            secure: i1Dr0k393wXBsCKST5ckeTPdZT+hjkikHCGgMSEkJxw+Q8m/Sgq9bbBalkJZDZDc8t0a/nE4ioEXoYO+PT9wRSpjLbjDVwRoWde5PVHaR3JviiwxULEynFLbvdJ1S2O/zRM37YMVgIIXN/2SWSXvQcQznrrvjtBoV+nZfYHX2WZQruq1nQXcPvTJPeZtCBsWaA3TwbVobnOJdb3TFxnHybN3N4gCTOkurek0V7OSMpjd1qgSzNMDIhjXKf/ZB9bcuusXo2QSnzUDJo3S6QE4FBxKohVom7z4AQ8+iRVPkkrWezBo089vzPzfZN/C5+8xQAUfZ6bVNdS6DfI80+55s6Xj7BFEKQW9Kh3Em0GpipHxdxiBf176xktY9EROkDkwDHlsbE7JRRQUmfmJe+0yCo+gg9uAsz5XHNrQgU5BxKhVzggMA/VU+clJ51WfbYGJAvVs/NjHQb/A9CzYKdBamUvy3YY2dxLbdohR7TZMM0JWYmZcmSiaOiZxrCT3ThlQ/J9o9r6TFWvkVjvt+ozABsx0OvtNrdkp7VvFbSQGvmTzGnPM2O5xqzWrM73Z7g8Ahw1g08FDN0JAO8n/Y0tb/xpVAFBmkQTJpQk7f4kQAHWlZKEYN2wEnX+hptjXfDjMYGX9Tc5vdDQJ3oTxnCt+y7Vl9IplT0a5GTTE0l8Pyc4=
          file_glob: true
          file: '*.{deb,rpm}'
          on:
            repo: ParallelSSH/ssh2-python
            tags: true

    - stage: build packages
      os: linux
      python: 3.6
      env:
        - WHEELS=1
      install:
        - pip install twine
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - ./ci/travis/build-manylinux.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload -u $PYPI_U -p $PYPI_P wheelhouse/*.whl;
          fi
      deploy:
        - provider: pypi
          skip_cleanup: true
          on:
            repo: ParallelSSH/ssh2-python
            tags: true
          distributions: sdist
          user: pkittenis
          password:
            secure: "eEBo76bmNWArLOzLNkv8whYO81HqkYpwUu3RqBHv6PNW/sI70VSIVfPTWo8ThlNkYSBy1Sxci6eU+Vd8qYH/vaCbl4068BkzroGUqGMLHXLRLEPQjO2pxTvnQ7Nbj/Mi9enoslLJKflx2USy2iPz1yGCWZrPzjLWmEMcx6j5e3fEUGF2p6p01w/zWxmiSoyJgBsby9P8Fl5nflsNMVR/or8frK4K1T6Y2oTuEx9aYymmBPFOO5DHaedDxnhZ04KKaACIECvKrT5V3PMM1jrE3qu6hJ1LS0/mSivEdCwCszHanjIQy/enkNtLgxVm4jIRUjuAwL1MmxPtkAUcKrQor1YokMqm5fExdwvnp+qjtyejfA3IvT93nYvCj4IEYNMDtUGFUBjsYLqg7Ked/jvO53Ek5WEAE/Mx8F/OAtuvkpEeUKTIWxfd+V0b7pgShVuU5zFyi3y97vpRtdwqzOFr8QT3Hq+g/RIdghPQ9pGQ3GOomTMO1B7mAyOG6SYyQM/wra2h2dQTHCbgzAtsPzZLiZhWIGcU7/mGLm0kZBT6McnH2//hsIPXG8S94u2MWE0KRH5YhJ/2ATWneYyFHWQfwqDeR/1CZe66gFcPJ9cOIG+8pcmXueLhnueDbh2EWa8jmumtrAz+z+rcokih0c7catT7pByDv24Ouuw2Yf3my60="
