language: python
cache:
  - pip
  - directories:
      - "$HOME/.pyenv"
notifications:
  email: false
sudo: required
dist: xenial
services:
  - docker
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
addons:
  apt:
    packages:
      - openssh-server
      - rpm
      - dpkg
      - cmake
install:
  - pip install flake8 jinja2 sphinx sphinx_rtd_theme
  - python setup.py build_ext --inplace
  - eval "$(ssh-agent -s)"
script:
  - pytest tests
  - flake8 ssh2
  # Test source distribution builds
  - python setup.py sdist
  - cd dist
  - pip install *
  - python -c 'from ssh2.session import Session; Session()'
  - cd ..
  - cd doc
  - make html
  - cd ..

jobs:
  include:

    - &osx-wheels
      stage: build packages
      os: osx
      osx_image: xcode9.2
      env:
        - SYSTEM_LIBSSH2: 1
      before_install:
        - brew update
        - brew outdated openssl || travis_wait brew upgrade openssl || echo "y"
        - brew link --overwrite python@2 || brew install python@2 || brew link --overwrite python@2
        - which python2
        - python2 -c "from __future__ import print_function; import ssl; from platform import python_version; print(ssl.OPENSSL_VERSION); print(python_version())"
        - sudo -H pip2 install twine
        - which twine
        - sudo ci/install-ssh2.sh
        - cp /usr/local/lib/libssh2* .
        - mkdir -p wheels
      install:
        - sudo -H pip2 install -U delocate wheel pip setuptools
        - ls -lh
      script:
        - pip2 wheel .
        - delocate-listdeps --all *.whl
        - delocate-wheel -v *.whl
        - delocate-listdeps --all *.whl
        - ls -l *.whl
        - rm -f *.dylib
        - pip2 install --user -v *.whl
        - pwd; mkdir temp; cd temp; pwd
        - python -c "from ssh2.session import Session; Session()"
        - cd ..; pwd
        - mv -f *.whl wheels/
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheels/*.whl;
          fi
      language: generic
      python: skip

    - <<: *osx-wheels
      osx_image: xcode9.2

    - <<: *osx-wheels
      osx_image: xcode9.2
      env:
        - PYENV: 3.6.4
        - SYSTEM_LIBSSH2: 1
      install: skip
      script:
        - travis_wait ./ci/travis/pyenv-wheel.sh

    - <<: *osx-wheels
      osx_image: xcode9.4
      env:
        - PYENV: 3.6.4
        - SYSTEM_LIBSSH2: 1
      install: skip
      script:
        - travis_wait ./ci/travis/pyenv-wheel.sh

    - <<: *osx-wheels
      osx_image: xcode9.2
      env:
        - PYENV: 3.7.0
        - SYSTEM_LIBSSH2: 1
      install: skip
      script:
        - travis_wait ./ci/travis/pyenv-wheel.sh

    - <<: *osx-wheels
      osx_image: xcode9.4
      env:
        - PYENV: 3.7.0
        - SYSTEM_LIBSSH2: 1
      install: skip
      script:
        - travis_wait ./ci/travis/pyenv-wheel.sh

    - stage: build packages
      os: linux
      python: 3.6
      env:
        - WHEELS=1
      install:
        - pip install twine
      script:
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
        - ./ci/travis/build-manylinux.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheelhouse/*.whl;
          fi
      deploy:
        - provider: pypi
          skip_cleanup: true
          on:
            repo: ParallelSSH/ssh2-python
            tags: true
          distributions: sdist
          user: pkittenis
          password:
            secure: "eEBo76bmNWArLOzLNkv8whYO81HqkYpwUu3RqBHv6PNW/sI70VSIVfPTWo8ThlNkYSBy1Sxci6eU+Vd8qYH/vaCbl4068BkzroGUqGMLHXLRLEPQjO2pxTvnQ7Nbj/Mi9enoslLJKflx2USy2iPz1yGCWZrPzjLWmEMcx6j5e3fEUGF2p6p01w/zWxmiSoyJgBsby9P8Fl5nflsNMVR/or8frK4K1T6Y2oTuEx9aYymmBPFOO5DHaedDxnhZ04KKaACIECvKrT5V3PMM1jrE3qu6hJ1LS0/mSivEdCwCszHanjIQy/enkNtLgxVm4jIRUjuAwL1MmxPtkAUcKrQor1YokMqm5fExdwvnp+qjtyejfA3IvT93nYvCj4IEYNMDtUGFUBjsYLqg7Ked/jvO53Ek5WEAE/Mx8F/OAtuvkpEeUKTIWxfd+V0b7pgShVuU5zFyi3y97vpRtdwqzOFr8QT3Hq+g/RIdghPQ9pGQ3GOomTMO1B7mAyOG6SYyQM/wra2h2dQTHCbgzAtsPzZLiZhWIGcU7/mGLm0kZBT6McnH2//hsIPXG8S94u2MWE0KRH5YhJ/2ATWneYyFHWQfwqDeR/1CZe66gFcPJ9cOIG+8pcmXueLhnueDbh2EWa8jmumtrAz+z+rcokih0c7catT7pByDv24Ouuw2Yf3my60="
